"""
bubblegum/convert/emitters/feature.py
=====================================
Emit a normalized Gherkin ``.feature`` file for one Feature/Epic.

The output is clean, canonical Gherkin (proper Given/When/Then indentation,
one scenario per source row, tags for Jira/persona/backend). It is both a
human-reviewable artifact *and* the file the Python/TypeScript step definitions
bind to.
"""

from __future__ import annotations

from bubblegum.convert.models import Feature, Scenario, StepKind

_GENERATED_BANNER = (
    "# Generated by `bubblegum convert` — review before running.\n"
    "# Steps marked NEEDS_DATA / MANUAL / BACKEND need a human before they pass.\n"
)

_KEYWORD_TITLE = {"given": "Given", "when": "When", "then": "Then"}


def _step_line(prev_section: str | None, section: str, text: str) -> str:
    """Render a step, using 'And' when it repeats the previous section."""
    if prev_section == section:
        keyword = "And"
    else:
        keyword = _KEYWORD_TITLE.get(section, "Given")
    return f"    {keyword} {text}"


def _scenario_block(scenario: Scenario) -> str:
    lines: list[str] = []
    if scenario.tags:
        lines.append("  " + " ".join(scenario.tags))
    lines.append(f"  Scenario: {scenario.title}")

    prev: str | None = None
    for step in scenario.steps:
        lines.append(_step_line(prev, step.keyword, step.text))
        # Annotate non-automatable steps inline so reviewers see the gap.
        if step.kind is not StepKind.AUTO:
            lines.append(f"    # ^ {step.kind.value.upper()}: {step.todo}")
        prev = step.keyword
    return "\n".join(lines)


def emit_feature_file(feature: Feature) -> str:
    """Return the full text of a ``.feature`` file for a Feature group."""
    parts: list[str] = [_GENERATED_BANNER]
    if feature.tags:
        parts.append(" ".join(feature.tags))
    parts.append(f"Feature: {feature.name}\n")
    parts.append("\n\n".join(_scenario_block(s) for s in feature.scenarios))
    return "\n".join(parts).rstrip() + "\n"
