"""
bubblegum/convert/emitters/python_bdd.py
========================================
Emit Python step definitions (pytest-bdd) that bind to a generated
``.feature`` file and drive Bubblegum's ``act`` / ``verify`` / ``extract``.

AUTO steps become a real call. NEEDS_DATA / MANUAL / BACKEND steps become an
explicit ``pytest.skip`` with the reason, so a scaffold run is honest: nothing
silently passes on a step a human still has to finish.

The generated module expects a ``page`` fixture (Playwright) — the same
contract as Bubblegum's own examples. Steps are async; run with
``pytest-asyncio`` + the ``web`` extra installed.
"""

from __future__ import annotations

from bubblegum.convert.emitters.stepcall import primitive_for, py_escape
from bubblegum.convert.models import Feature, StepKind
from bubblegum.convert.profile import ConvertProfile

_PY_KEYWORD = {"given": "given", "when": "when", "then": "then"}


def _func_name(section: str, index: int) -> str:
    return f"step_{section}_{index}"


def emit_python_steps(
    feature: Feature,
    feature_filename: str,
    profile: ConvertProfile | None = None,
) -> str:
    """Return the text of a pytest-bdd step-definition module for a Feature."""
    profile = profile or ConvertProfile()

    header = [
        '"""',
        f"Generated by `bubblegum convert` for feature: {feature.name}",
        "Review before running. AUTO steps call Bubblegum; other steps skip with",
        "a TODO reason until a human wires the locator / data / backend.",
        "",
        "Requires: pytest, pytest-bdd, pytest-asyncio, and a `page` fixture",
        "(Playwright). See docs/getting-started-for-testers.md.",
        '"""',
        "from __future__ import annotations",
        "",
        "import pytest",
        "from pytest_bdd import scenarios, given, when, then",
        "",
        profile.output.bubblegum_import,
        "",
        f'scenarios("{feature_filename}")',
        "",
    ]

    body: list[str] = []
    # Deduplicate identical (section, text) steps so pytest-bdd doesn't see two
    # handlers for the same phrase.
    seen: set[tuple[str, str]] = set()
    counter = 0

    for scenario in feature.scenarios:
        for step in scenario.steps:
            key = (step.keyword, step.text)
            if key in seen:
                continue
            seen.add(key)
            counter += 1

            decorator = _PY_KEYWORD.get(step.keyword, "given")
            escaped = py_escape(step.text)
            fn = _func_name(step.keyword, counter)
            body.append(f'@{decorator}("{escaped}")')
            body.append(f"async def {fn}(page):")

            if step.kind is StepKind.AUTO:
                prim = primitive_for(step)
                instr = py_escape(step.instruction)
                body.append(f'    await {prim}("{instr}", page=page)')
            else:
                reason = (step.todo or step.kind.value).replace('"', "'")
                body.append(f'    # {step.kind.value.upper()}: {reason}')
                body.append(f'    pytest.skip("{step.kind.value.upper()}: {py_escape(reason)}")')
            body.append("")

    return "\n".join(header + body).rstrip() + "\n"
