"""
bubblegum/convert/emitters/ts_smart.py
======================================
Emit "smart-tests"-style TypeScript: a reusable ``<feature>.flow.ts`` (one
exported async function per scenario) plus a thin ``<feature>.test.mts`` that
composes them with setup / login / reporting — matching the user's
``smart-tests/`` architecture (helpers + flows + tests).

Each AUTO step becomes a real ``act`` / ``verify`` call through the shared
wrapper helpers. Navigation steps get the team's wait pattern
(``waitForLoadState`` + ``waitForTimeout``). Login-persona preconditions are
handled once by ``loginFlow`` in the test, not repeated per flow. Non-AUTO steps
are emitted as ``// TODO`` with the best-guess call commented out.
"""

from __future__ import annotations

import re

from bubblegum.convert.emitters.stepcall import (
    act_phrase,
    is_nav_step,
    primitive_for,
    ts_escape,
    verify_phrase,
)
from bubblegum.convert.models import Feature, Scenario, StepKind
from bubblegum.convert.profile import ConvertProfile

_BANNER = (
    "/**\n"
    " * Generated by `bubblegum convert` — review before running.\n"
    " * AUTO steps call Bubblegum; TODO steps need a human (locator / data / backend).\n"
    " */\n"
)


def _is_login_step(step) -> bool:
    return step.kind is StepKind.NEEDS_DATA and bool(step.todo) and step.todo.startswith("Login")


def _fn_name(title: str, used: set[str]) -> str:
    """camelCase function name from a scenario title, unique within ``used``."""
    words = re.findall(r"[A-Za-z0-9]+", title)
    # Drop a leading "verify" — it's on almost every title and adds no signal.
    if words and words[0].lower() == "verify":
        words = words[1:]
    words = words[:6] or ["scenario"]
    name = words[0].lower() + "".join(w.capitalize() for w in words[1:])
    if not name[0].isalpha():
        name = "s_" + name
    base = name
    n = 2
    while name in used:
        name = f"{base}{n}"
        n += 1
    used.add(name)
    return name


def _wait_block(indent: str, profile: ConvertProfile) -> list[str]:
    if profile.wait_strategy == "none":
        return []
    return [
        f"{indent}await page.waitForLoadState('domcontentloaded');",
        f"{indent}await page.waitForTimeout(3000);",
    ]


def _render_step(step, profile: ConvertProfile) -> list[str]:
    """Render one CanonicalStep into flow-body lines."""
    ind = "  "
    if _is_login_step(step):
        return [f"{ind}// Login precondition — handled by loginFlow() in the test setup."]

    if step.kind is StepKind.AUTO:
        if primitive_for(step) == "verify":
            phrase = ts_escape(verify_phrase(step))
            return [f"{ind}await verify(engine, '{phrase}');"]
        phrase = ts_escape(act_phrase(step))
        lines = [f"{ind}await act(engine, '{phrase}');"]
        if is_nav_step(step):
            lines += _wait_block(ind, profile)
        return lines

    # NEEDS_DATA / MANUAL / BACKEND → pending, best-guess call commented out.
    prim = primitive_for(step)
    phrase = ts_escape(act_phrase(step) if prim != "verify" else verify_phrase(step))
    reason = (step.todo or step.kind.value)
    return [
        f"{ind}// TODO ({step.kind.value.upper()}): {reason}",
        f"{ind}// await {prim}(engine, '{phrase}');",
    ]


def _scenario_fn(scenario: Scenario, fn: str, profile: ConvertProfile) -> str:
    lines = [
        f"/** {scenario.title} */",
        f"export async function {fn}(engine: Bubblegum, page: Page): Promise<void> {{",
    ]
    for step in scenario.steps:
        lines.extend(_render_step(step, profile))
    safe_title = ts_escape(scenario.title)
    lines.append(f"  console.log('{safe_title} — done');")
    lines.append("}")
    return "\n".join(lines)


def emit_flow_file(feature: Feature, fn_names: list[str], profile: ConvertProfile | None = None) -> str:
    """Return the ``<feature>.flow.ts`` text. ``fn_names`` aligns 1:1 with scenarios."""
    profile = profile or ConvertProfile()
    helpers = profile.output.ts_helpers_dir.rstrip("/")
    parts = [
        _BANNER,
        "import type { Page } from '@playwright/test';",
        "import type { Bubblegum } from '@bubblegum-ai/node';",
        f"import {{ act, verify, observe }} from '{helpers}/actions';",
        "",
        "\n\n".join(
            _scenario_fn(s, fn, profile) for s, fn in zip(feature.scenarios, fn_names)
        ),
    ]
    return "\n".join(parts).rstrip() + "\n"


def emit_test_file(feature: Feature, fn_names: list[str], profile: ConvertProfile | None = None) -> str:
    """Return the ``<feature>.test.mts`` text that composes the feature's flows."""
    profile = profile or ConvertProfile()
    helpers = profile.output.ts_helpers_dir.rstrip("/")
    flows = profile.output.ts_flows_dir.rstrip("/")

    needs_login = any(
        _is_login_step(step) for s in feature.scenarios for step in s.steps
    )
    persona = next((s.persona for s in feature.scenarios if s.persona), "")

    imports = [
        "import dotenv from 'dotenv';",
        f"import {{ initEngine, teardownEngine, type EngineContext }} from '{helpers}/engine';",
        f"import {{ generateReports }} from '{helpers}/reporter';",
    ]
    if needs_login:
        imports.append(f"import {{ loginFlow }} from '{flows}/login.flow';")
    imported = ", ".join(fn_names)
    imports.append(f"import {{ {imported} }} from '{flows}/{feature.slug}.flow';")

    setup = [
        "dotenv.config({ path: '.env.bubblegum.local' });",
        "",
        "// TODO: point these at your project's constants/data modules.",
        "const APP_URL = process.env.APP_URL ?? 'https://your-app.example.com';",
    ]
    if needs_login:
        setup += [
            "const credentials = {",
            "  username: process.env.APP_USER ?? '',",
            "  password: process.env.APP_PASS ?? '',",
            "};",
        ]

    body = [
        "async function main() {",
        "  let ctx: EngineContext | null = null;",
        "  try {",
        "    ctx = await initEngine();",
        "    const { page, engine } = ctx;",
        "",
        "    await page.goto(APP_URL, { waitUntil: 'networkidle', timeout: 30000 });",
        "    console.log('Page opened successfully');",
        "",
    ]
    if needs_login:
        body.append(f"    // persona: {persona or 'user'}")
        body.append("    await loginFlow(engine, page, credentials);")
        body.append("")
    for fn in fn_names:
        body.append(f"    await {fn}(engine, page);")
    body += [
        "",
        f"    console.log('{ts_escape(feature.name)} — all scenarios completed');",
        "  } catch (error) {",
        "    console.error('Test failed:', error);",
        "    process.exitCode = 1;",
        "  } finally {",
        "    if (ctx) {",
        "      try {",
        f"        await generateReports(ctx.engine, {{ title: '{ts_escape(feature.name)}', suiteName: '{feature.slug}' }});",
        "      } catch {",
        "        // report failure should not mask test failure",
        "      }",
        "      await teardownEngine(ctx);",
        "    }",
        "  }",
        "}",
        "",
        "main();",
    ]

    return "\n".join([_BANNER, *imports, "", *setup, "", *body]).rstrip() + "\n"
