"""
bubblegum/convert/emitters/ts_smart.py
======================================
Emit "smart-tests"-style TypeScript: a reusable ``<feature>.flow.ts`` (one
exported async function per scenario) plus a thin ``<feature>.test.mts`` that
composes them with setup / login / reporting — matching the user's
``smart-tests/`` architecture (helpers + flows + tests).

Each AUTO step becomes a real ``act`` / ``verify`` call through the shared
wrapper helpers. Navigation steps get the team's wait pattern
(``waitForLoadState`` + ``waitForTimeout``). Login-persona preconditions are
handled once by ``loginFlow`` in the test, not repeated per flow. Non-AUTO steps
are emitted as ``// TODO`` with the best-guess call commented out.
"""

from __future__ import annotations

import re

from bubblegum.convert.emitters.stepcall import (
    act_phrase,
    is_nav_step,
    primitive_for,
    ts_escape,
    verify_phrase,
)
from bubblegum.convert.emitters.tsdata import ScenarioData, extract_scenario_data
from bubblegum.convert.models import Feature, Scenario, StepKind
from bubblegum.convert.profile import ConvertProfile


def _bt_escape(text: str) -> str:
    """Escape a string for a TS backtick template, preserving ${...} interpolation."""
    return text.replace("\\", "\\\\").replace("`", "\\`")


def _scenario_data_list(feature: Feature, fn_names: list[str], profile: ConvertProfile) -> list:
    """Per-scenario ScenarioData (or None), aligned with feature.scenarios."""
    if not profile.output.extract_data:
        return [None] * len(feature.scenarios)
    return [
        extract_scenario_data(s, f"{fn}Data") for s, fn in zip(feature.scenarios, fn_names)
    ]

_BANNER = (
    "/**\n"
    " * Generated by `bubblegum convert` — review before running.\n"
    " * AUTO steps call Bubblegum; TODO steps need a human (locator / data / backend).\n"
    " */\n"
)


def _is_login_step(step) -> bool:
    return step.kind is StepKind.NEEDS_DATA and bool(step.todo) and step.todo.startswith("Login")


def _report_title(name: str, profile: ConvertProfile) -> str:
    prefix = profile.project.report_title_prefix
    return f"{prefix} {name}".strip() if prefix else name


_VAR_SET_RE = re.compile(r"as\s+([A-Za-z_]\w*)\s*\}\}")
_VAR_USE_RE = re.compile(r"\{\{\$([A-Za-z_]\w*)\}\}")


def _dependency_notes(scenarios) -> dict[int, str]:
    """Map scenario index → note when it uses a session var an earlier one sets.

    Detects Bubblegum session variables: a scenario that references ``{{$var}}``
    depends on the earliest scenario that defined it with ``as var``.
    """
    setters: dict[str, tuple[int, str]] = {}
    notes: dict[int, str] = {}
    for i, scenario in enumerate(scenarios):
        blob = " ".join(step.text for step in scenario.steps)
        used = {m for m in _VAR_USE_RE.findall(blob)}
        for var in sorted(used):
            if var in setters and setters[var][0] < i:
                idx, title = setters[var]
                notes[i] = f"scenario {idx + 1} ({title}) — sets {{{{${var}}}}}"
        for var in _VAR_SET_RE.findall(blob):
            setters.setdefault(var, (i, scenario.title))
    return notes


def _fn_name(title: str, used: set[str]) -> str:
    """camelCase function name from a scenario title, unique within ``used``."""
    words = re.findall(r"[A-Za-z0-9]+", title)
    # Drop a leading "verify" — it's on almost every title and adds no signal.
    if words and words[0].lower() == "verify":
        words = words[1:]
    words = words[:6] or ["scenario"]
    name = words[0].lower() + "".join(w.capitalize() for w in words[1:])
    if not name[0].isalpha():
        name = "s_" + name
    base = name
    n = 2
    while name in used:
        name = f"{base}{n}"
        n += 1
    used.add(name)
    return name


def _wait_block(indent: str, profile: ConvertProfile) -> list[str]:
    if profile.wait_strategy == "none":
        return []
    return [
        f"{indent}await page.waitForLoadState('domcontentloaded');",
        f"{indent}await page.waitForTimeout(3000);",
    ]


# "open/navigate to the <X> page" → a navigation the project config can map.
_NAV_PAGE_RE = re.compile(
    r"^(?:open|navigate\s+to|go\s+to|view)\s+(?:the\s+)?(.+?)\s+(?:page|screen)\b",
    re.IGNORECASE,
)


def _nav_page_name(instruction: str) -> str | None:
    m = _NAV_PAGE_RE.match((instruction or "").strip())
    return m.group(1).strip() if m else None


def _nav_lookup(page: str, profile: ConvertProfile) -> dict[str, str] | None:
    nav = profile.project.navigation
    if page in nav:
        return nav[page]
    key = page.casefold()
    for name, spec in nav.items():
        if name.casefold() == key:
            return spec
    return None


def _custom_code(step, profile: ConvertProfile) -> str | None:
    text = step.text.casefold()
    for p in profile.project.custom_patterns:
        if p["pattern"] and p["pattern"].casefold() in text:
            return p["code"]
    return None


def _emit_call(prim: str, phrase: str) -> str:
    """Bubblegum call; template expressions ({{..}}) MUST bypass the wrapper and
    hit engine.act/engine.verify directly (the wrapper doesn't process them)."""
    esc = ts_escape(phrase)
    if "{{" in phrase:
        return f"await engine.{'verify' if prim == 'verify' else 'act'}('{esc}');"
    fn = "verify" if prim == "verify" else "act"
    return f"await {fn}(engine, '{esc}');"


def _render_nav(mapped: dict[str, str], page: str, ind: str, profile: ConvertProfile) -> list[str]:
    if mapped.get("type") == "url" and mapped.get("path"):
        return [f"{ind}await page.goto('{ts_escape(mapped['path'])}');", *_wait_block(ind, profile)]
    action = mapped.get("action") or f"Click the {page} menu"
    return [
        f"{ind}await observe(engine, 'the {ts_escape(page)} menu');",
        f"{ind}await act(engine, '{ts_escape(action)}');",
        *_wait_block(ind, profile),
    ]


def _render_step(step, profile: ConvertProfile, data: ScenarioData | None = None) -> list[str]:
    """Render one CanonicalStep into flow-body lines."""
    ind = "  "

    # 1) Project-defined custom pattern wins (escape hatch for literal code).
    code = _custom_code(step, profile)
    if code is not None:
        return [f"{ind}{line}" if line else "" for line in code.split("\n")]

    # 2) Login precondition is handled once in the test setup.
    if _is_login_step(step):
        return [f"{ind}// Login precondition — handled by loginFlow() in the test setup."]

    if step.kind is StepKind.AUTO:
        # 3) Navigation the project config knows how to reach.
        page = _nav_page_name(step.instruction)
        if page:
            mapped = _nav_lookup(page, profile)
            if mapped:
                return _render_nav(mapped, page, ind, profile)

        # 4) A static literal extracted into the data file → interpolate it.
        if data is not None and step.value and "{{" not in step.value:
            key = data.lookup.get((step.target or "value", step.value))
            if key:
                tpl = act_phrase(step).replace(
                    f'"{step.value}"', f'"${{{data.object_name}.{key}}}"', 1
                )
                lines = [f"{ind}await act(engine, `{_bt_escape(tpl)}`);"]
                if is_nav_step(step):
                    lines += _wait_block(ind, profile)
                return lines

        prim = primitive_for(step)
        phrase = verify_phrase(step) if prim == "verify" else act_phrase(step)
        lines = [f"{ind}{_emit_call(prim, phrase)}"]
        if prim != "verify" and is_nav_step(step):
            lines += _wait_block(ind, profile)
        return lines

    # NEEDS_DATA / MANUAL / BACKEND → pending, best-guess call commented out.
    prim = primitive_for(step)
    phrase = ts_escape(act_phrase(step) if prim != "verify" else verify_phrase(step))
    reason = (step.todo or step.kind.value)
    return [
        f"{ind}// TODO ({step.kind.value.upper()}): {reason}",
        f"{ind}// await {prim}(engine, '{phrase}');",
    ]


def _scenario_blocks(scenario: Scenario, profile: ConvertProfile, data: ScenarioData | None):
    """Per-step rendered blocks (each a tuple of indented source lines)."""
    return [tuple(_render_step(step, profile, data)) for step in scenario.steps]


def _scenario_fn_from_blocks(scenario: Scenario, fn: str, blocks) -> str:
    doc = ["/**", f" * {scenario.title}"]
    if scenario.jira:
        doc.append(f" * Jira: {scenario.jira}")
    doc.append(" */")
    lines = [*doc, f"export async function {fn}(engine: Bubblegum, page: Page): Promise<void> {{"]
    for block in blocks:
        lines.extend(block)
    lines.append(f"  console.log('Scenario passed: {ts_escape(scenario.title)}');")
    lines.append("}")
    return "\n".join(lines)


def _shared_fn_src(name: str, body_lines: list[str]) -> str:
    return "\n".join([
        "/** Shared steps extracted from multiple scenarios. */",
        f"export async function {name}(engine: Bubblegum, page: Page): Promise<void> {{",
        *body_lines,
        "}",
    ])


def emit_flow_file(feature: Feature, fn_names: list[str], profile: ConvertProfile | None = None) -> str:
    """Return the ``<feature>.flow.ts`` text. ``fn_names`` aligns 1:1 with scenarios."""
    profile = profile or ConvertProfile()
    helpers = profile.output.ts_helpers_dir.rstrip("/")
    data_dir = profile.output.ts_data_dir.rstrip("/")
    data_list = _scenario_data_list(feature, fn_names, profile)

    imports = [
        "import type { Page } from '@playwright/test';",
        "import type { Bubblegum } from '@bubblegum-ai/node';",
        f"import {{ act, verify, observe }} from '{helpers}/actions';",
    ]
    used_objs = [d.object_name for d in data_list if d is not None]
    if used_objs:
        imports.append(
            f"import {{ {', '.join(used_objs)} }} from '{data_dir}/{feature.slug}.data';"
        )

    per_scenario = [
        _scenario_blocks(s, profile, d)
        for s, d in zip(feature.scenarios, data_list)
    ]

    shared_srcs: list[str] = []
    if profile.output.dedup_subflows:
        from bubblegum.convert.emitters.dedup import dedup_scenarios

        shared, per_scenario = dedup_scenarios(per_scenario)
        shared_srcs = [_shared_fn_src(name, body) for name, body in shared]

    scenario_srcs = [
        _scenario_fn_from_blocks(s, fn, blocks)
        for s, fn, blocks in zip(feature.scenarios, fn_names, per_scenario)
    ]

    parts = [_BANNER, *imports, ""]
    parts.append("\n\n".join([*shared_srcs, *scenario_srcs]))
    return "\n".join(parts).rstrip() + "\n"


def emit_data_file(feature: Feature, fn_names: list[str], profile: ConvertProfile | None = None) -> str | None:
    """Return the ``<feature>.data.ts`` text, or None when nothing to extract."""
    profile = profile or ConvertProfile()
    data_list = _scenario_data_list(feature, fn_names, profile)
    objs = [d for d in data_list if d is not None]
    if not objs:
        return None

    blocks = []
    for d in objs:
        lines = [f"export const {d.object_name} = {{"]
        for key, value in d.entries:
            lines.append(f"  {key}: '{ts_escape(value)}',")
        lines.append("};")
        blocks.append("\n".join(lines))

    header = (
        "/**\n"
        f" * Test data for {feature.name} — generated by `bubblegum convert`.\n"
        " * Edit values here; the flows reference these constants.\n"
        " */\n"
    )
    return header + "\n" + "\n\n".join(blocks) + "\n"


def emit_test_file(feature: Feature, fn_names: list[str], profile: ConvertProfile | None = None) -> str:
    """Return the ``.test.mts`` text: one runnable file with one test per scenario.

    Each scenario flow function is invoked as an isolated, labeled "test" — a
    failure in one is caught and reported without aborting the rest — and all
    steps land in a single aggregated Bubblegum report. ``feature`` may be a real
    Feature/Epic group or a whole-workbook bundle; ``feature.name``/``slug`` name
    the file and report.
    """
    profile = profile or ConvertProfile()
    helpers = profile.output.ts_helpers_dir.rstrip("/")
    flows = profile.output.ts_flows_dir.rstrip("/")

    needs_login = any(
        _is_login_step(step) for s in feature.scenarios for step in s.steps
    )
    persona = next((s.persona for s in feature.scenarios if s.persona), "")

    proj = profile.project

    imports = [
        "import dotenv from 'dotenv';",
        f"import {{ initEngine, teardownEngine, type EngineContext }} from '{helpers}/engine';",
        f"import {{ generateReports }} from '{helpers}/reporter';",
    ]
    if needs_login:
        imports.append(f"import {{ loginFlow }} from '{flows}/login.flow';")

    # Base URL: a project import if configured, else an env var.
    if proj.base_url_import:
        imports.append(
            f"import {{ {proj.base_url_import['export']} }} from '{proj.base_url_import['module']}';"
        )
    # Credentials for the login persona: a project import if mapped, else a
    # placeholder object populated from the environment.
    creds = proj.persona_credentials(persona) if needs_login else None
    if needs_login and creds and creds.get("function") and creds.get("module"):
        imports.append(f"import {{ {creds['function']} }} from '{creds['module']}';")

    imported = ", ".join(fn_names)
    imports.append(f"import {{ {imported} }} from '{flows}/{feature.slug}.flow';")

    # Cleanup: only when configured AND a scenario creates data ({{... as var}}).
    creation_vars: list[str] = []
    for s in feature.scenarios:
        blob = " ".join(step.text for step in s.steps)
        for var in _VAR_SET_RE.findall(blob):
            if var not in creation_vars:
                creation_vars.append(var)
    cleanup_cfg = proj.cleanup if creation_vars else None
    cleanup_type = "Record<string, string | undefined>"
    if cleanup_cfg:
        module = cleanup_cfg["module"]
        fn = cleanup_cfg["function"]
        if module.endswith("cleanup.flow"):
            imports.append(f"import {{ {fn}, type CleanupData }} from '{module}';")
            cleanup_type = "CleanupData"
        else:
            imports.append(f"import {{ {fn} }} from '{module}';")

    setup = ["dotenv.config({ path: '.env.bubblegum.local' });", ""]
    if proj.base_url_import:
        setup.append(f"const APP_URL = {proj.base_url_import['export']};")
    else:
        setup.append(
            f"const APP_URL = process.env.{proj.base_url_env} ?? 'https://your-app.example.com';"
        )
    if needs_login:
        if creds and creds.get("function"):
            setup.append(f"const credentials = {creds['function']}();")
        else:
            setup += [
                "// TODO: map this persona to your project's credentials module",
                "// (see convert.personas in bubblegum.convert.yaml).",
                "const credentials = {",
                "  username: process.env.APP_USER ?? '',",
                "  password: process.env.APP_PASS ?? '',",
                "};",
            ]

    # Registry of test methods: [label, flow function]. One entry per scenario.
    # Annotate scenarios that consume a session variable an earlier scenario set.
    deps = _dependency_notes(feature.scenarios)
    registry = ["// One test method per scenario in this workbook.", "const tests: Array<[string, (engine: any, page: any) => Promise<void>]> = ["]
    for i, (scenario, fn) in enumerate(zip(feature.scenarios, fn_names)):
        if deps.get(i):
            registry.append(f"  // Depends on: {deps[i]}")
        registry.append(f"  ['{ts_escape(scenario.title)}', {fn}],")
    registry.append("];")

    body = [
        "async function main() {",
        "  let ctx: EngineContext | null = null;",
        "  let failures = 0;",
    ]
    if cleanup_cfg:
        body.append(f"  const cleanupData: {cleanup_type} = {{}};")
    body += [
        "  try {",
        "    ctx = await initEngine();",
        "    const { page, engine } = ctx;",
        "",
        "    await page.goto(APP_URL, { waitUntil: 'networkidle', timeout: 30000 });",
        "    console.log('Page opened successfully');",
        "",
    ]
    if needs_login:
        body.append(f"    // persona: {persona or 'user'}")
        body.append("    await loginFlow(engine, page, credentials);")
        body.append("")
    body += [
        "    for (const [name, testFn] of tests) {",
        "      console.log(`\\n=== TEST: ${name} ===`);",
        "      try {",
        "        await testFn(engine, page);",
        "        console.log(`PASS: ${name}`);",
        "      } catch (err) {",
        "        failures++;",
    ]
    if profile.project.on_failure_screenshot:
        body += [
            "        try {",
            "          await page.screenshot({ path: `${process.env.REPORT_DIR ?? 'reports'}/failure-${name.replace(/[^a-z0-9]+/gi, '_')}-${Date.now()}.png`, fullPage: true });",
            "        } catch { /* screenshot is best-effort */ }",
        ]
    body += [
        "        console.error(`FAIL: ${name} —`, err);",
        "      }",
        "    }",
    ]
    if cleanup_cfg:
        body.append("")
        body.append("    // TODO: capture the session variable(s) this run created so")
        body.append("    // cleanup can remove them (confirm your engine's variable API):")
        for var in creation_vars:
            body.append(f"    // cleanupData.{var} = /* value of {{{{${var}}}}} */;")
    body += [
        "  } catch (error) {",
        "    console.error('Test run setup failed:', error);",
        "    failures++;",
        "  } finally {",
        "    if (ctx) {",
        "      try {",
        f"        await generateReports(ctx.engine, {{ title: '{ts_escape(_report_title(feature.name, profile))}', suiteName: '{feature.slug}' }});",
        "      } catch {",
        "        // report failure should not mask test failures",
        "      }",
        "      await teardownEngine(ctx);",
        "    }",
        f"    console.log(`\\n{ts_escape(feature.name)}: ${{tests.length - failures}}/${{tests.length}} passed`);",
        "    process.exitCode = failures > 0 ? 1 : 0;",
    ]
    if cleanup_cfg:
        body.append(f"    await {cleanup_cfg['function']}(cleanupData);  // skips gracefully when empty")
    body += [
        "  }",
        "}",
        "",
        "main();",
    ]

    return "\n".join([_BANNER, *imports, "", *setup, "", *registry, "", *body]).rstrip() + "\n"
