"""
bubblegum/convert/emitters/typescript_bdd.py
============================================
Emit TypeScript step definitions (playwright-bdd) that bind to the same
generated ``.feature`` file and drive the ``@bubblegum-ai/node`` client.

Mirrors the Python emitter one-for-one: AUTO steps become a real ``act`` /
``verify`` / ``extract`` call; NEEDS_DATA / MANUAL / BACKEND steps become a
``test.skip`` with the TODO reason.
"""

from __future__ import annotations

from bubblegum.convert.emitters.stepcall import primitive_for, ts_escape
from bubblegum.convert.models import Feature, StepKind
from bubblegum.convert.profile import ConvertProfile

_TS_KEYWORD = {"given": "Given", "when": "When", "then": "Then"}


def emit_typescript_steps(
    feature: Feature,
    profile: ConvertProfile | None = None,
) -> str:
    """Return the text of a playwright-bdd step-definition file for a Feature."""
    profile = profile or ConvertProfile()

    header = [
        f"// Generated by `bubblegum convert` for feature: {feature.name}",
        "// Review before running. AUTO steps call Bubblegum; other steps skip",
        "// with a TODO reason until a human wires the locator / data / backend.",
        "import { createBdd } from 'playwright-bdd';",
        f"import {{ act, verify, extract }} from '{profile.output.ts_client_import}';",
        "",
        "const { Given, When, Then } = createBdd();",
        "",
    ]

    body: list[str] = []
    seen: set[tuple[str, str]] = set()

    for scenario in feature.scenarios:
        for step in scenario.steps:
            key = (step.keyword, step.text)
            if key in seen:
                continue
            seen.add(key)

            fn = _TS_KEYWORD.get(step.keyword, "Given")
            escaped = ts_escape(step.text)

            if step.kind is StepKind.AUTO:
                prim = primitive_for(step)
                instr = ts_escape(step.instruction)
                body.append(
                    f"{fn}('{escaped}', async ({{ page }}) => {{\n"
                    f"  await {prim}('{instr}', {{ page }});\n"
                    f"}});"
                )
            else:
                reason = (step.todo or step.kind.value)
                prim = primitive_for(step)
                # Pending step: no-op with an explicit TODO + the best-guess call
                # commented out, so nothing silently "passes" as automated.
                body.append(
                    f"{fn}('{escaped}', async ({{ page }}) => {{\n"
                    f"  // TODO ({step.kind.value.upper()}): {reason}\n"
                    f"  // await {prim}('{escaped}', {{ page }});\n"
                    f"}});"
                )
            body.append("")

    return "\n".join(header + body).rstrip() + "\n"
