"""Unit tests for the optional .feature / pytest-bdd emitters."""

from __future__ import annotations

from bubblegum.convert.emitters import emit_feature_file, emit_python_steps
from bubblegum.convert.emitters.stepcall import primitive_for
from bubblegum.convert.models import CanonicalStep, StepKind
from bubblegum.convert.normalize import build_features
from bubblegum.convert.models import RawScenario


def _feature():
    raw = RawScenario(
        row=1,
        steps_text=(
            'Given I am logged in as a "Shopper"\n'
            "And I open the Checkout page\n"
            'When I enter "SAVE10" into the Coupon code field\n'
            "And I click the Apply button\n"
            "Then I see the Discount applied message"
        ),
        fields={"feature": "[F][Web] Checkout", "title": "Apply coupon", "jira": "PROJ-1"},
    )
    return build_features([raw])[0]


def test_primitive_selection():
    assert primitive_for(CanonicalStep("then", "x", action_type="verify")) == "verify"
    assert primitive_for(CanonicalStep("when", "x", action_type="extract")) == "extract"
    # an action under a Then still emits act, not verify
    assert primitive_for(CanonicalStep("then", "x", action_type="click")) == "act"
    assert primitive_for(CanonicalStep("when", "x", action_type="type")) == "act"


def test_feature_file_has_banner_tags_and_annotations():
    text = emit_feature_file(_feature())
    assert text.startswith("# Generated by `bubblegum convert`")
    assert "Feature: [F][Web] Checkout" in text
    assert "@proj_1" in text
    assert "Scenario: Apply coupon" in text
    # login precondition annotated as NEEDS_DATA
    assert "NEEDS_DATA" in text
    # uses And for repeated section
    assert "And I open the Checkout page" in text


def test_python_emitter_auto_and_skip():
    text = emit_python_steps(_feature(), "../features/checkout.feature")
    assert 'scenarios("../features/checkout.feature")' in text
    assert "from bubblegum import act, verify, extract" in text
    # AUTO type step becomes an act call with subject-stripped instruction
    assert 'await act("enter \\"SAVE10\\" into the Coupon code field", page=page)' in text
    # AUTO then step becomes verify
    assert 'await verify("see the Discount applied message", page=page)' in text
    # NEEDS_DATA login precondition becomes a skip
    assert "pytest.skip(" in text


def test_python_dedupes_repeated_steps():
    raw = RawScenario(
        row=1,
        steps_text="Given I open X\nThen I see Y",
        fields={"feature": "F", "title": "one"},
    )
    raw2 = RawScenario(
        row=2,
        steps_text="Given I open X\nThen I see Z",
        fields={"feature": "F", "title": "two"},
    )
    feat = build_features([raw, raw2])[0]
    text = emit_python_steps(feat, "f.feature")
    # "I open X" appears in two scenarios but only one handler is generated
    assert text.count('@given("I open X")') == 1


